name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Set up mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Install modules
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm playwright:i

      - name: Verify
        run: pnpm verify

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm release
